### PR TITLE
feat: reset headers when ACTION_RESET_LOCAL is dispatched

### PR DESCRIPTION
**Pull request by thai-eh**
Hi there, as current `headers` response is not reset as it should be when you dispatch `ACTION_RESET_LOCAL`, this quick change aims to address that, thanks in advance!

### CODE REVIEW

**Review by phthhieu — APPROVED** [review]

**Review by anhdaueh — APPROVED** [review]

**Comment by tungv** [comment]
@tvkhoa you still owe me the test cases for resetter, don't forget that.

**Comment by tungv** [comment]
released to npm with v1.2.4

**Comment by tungv** [comment]
thanks

**Comment by tvkhoa** [comment]
ohm uhmmm who said that @tungv ? =)))

**Comment by thai-eh** [comment]
@tungv Thanks for the release, not sure why but I haven't seen the changes inside the v1.2.4 package though, can you help me take a look into it?

image

**Comment by tungv** [comment]
I released 1.2.5, can you double check?

**Comment by thai-eh** [comment]
Thanks @tungv, v1.2.5 seems to only include `package.json` and the readme files though, can you help me check that again?

image

**Comment by tungv** [comment]
oh ok, my bad. somehow in the npm version I'm using, prepublish script is no longer trigger when `npm publish` is called.
1.2.6 should fix that.

thank you for your patience.

**Comment by thai-eh** [comment]
@tungv It's working fine now, thanks a lot for your time!

**Pull request merged**
