### PR TITLE
chore: Export RESET_LOCAL constant

### PR DESCRIPTION
**Pull request by phamhoaivu911**
When implementing the resetter, @tvkhoa forgot to export `ACTION_RESET_LOCAL` constant. 
This PR is to do it.

### CODE REVIEW

**Comment by phamhoaivu911** [comment]
BTW, do you think we should remove the whole API data when users call `resetter()` without params @tungv ? I'll be happy to create another PR for it before releasing a new version 🤔

**Comment by tungv** [comment]
Thanks @phamhoaivu911 for this PR. It looks good to me.
If you call `resetter()`, `payload.data` will include `'data'` and therefore `state.[apiName].data` will be updated to undefined.

why do you need to remove the whole API subtree from state?

https://github.com/tungv/redux-api-call/blob/6273d2942bad9f1c833c3d623632bb39f2e292a3/packages/core/src/reducer.js#L74

**Comment by tungv** [comment]
btw, for some reason, you need to forget a subtree, I'd suggest to expose a new action creator, probably called `forget()` or `dispose()`

**Comment by phamhoaivu911** [comment]
Because while all the data is updated to undefined, there is still a key `headers` in the state of the apiName, which is quite useless at the time. Moreover, removing the API subtree make the state cleaner.

I also thought of a new action creator, but then I saw your [comment](https://github.com/tungv/redux-api-call/pull/15#pullrequestreview-31011584). So it's ok now to create a new `dispose` action creator?

**Comment by tungv** [comment]
I think so, if you change an existing API's behavior, it's a breaking change and would require a major semver update. New action creator in this case is fine.

**Comment by phamhoaivu911** [comment]
Thanks @tungv . I'll create another PR for it! 🚀

**Comment by tungv** [comment]
nice! I will wait for that PR before releasing a new npm version

**Pull request merged**
